name = "GregTech Frostpunk"
author = "Lev Sychev"
version = "1.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ca1d1bafbb47a11834a1ec64696e6ed9abee118bf90998ac191f7c16a41b578"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
