name = "GregTech Frostpunk"
author = "Lev Sychev"
version = "1.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4e3a91abf9757df0dd9f34dfdc3fb883473676f13fcd1589904d641decebf4c"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
