name = "GregTech Frostpunk"
author = "Lev Sychev"
version = "1.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbb161c7e75c867e15da0632b3565bb3a48ec7c285ab8868352626971e6dad6a"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
