name = "GregTech Frostpunk"
author = "Lev Sychev"
version = "1.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff702034aac9e5100775bc2a11022c230faf9915035b1929b1f6f4896fe0a143"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
