name = "GregTech Frostpunk"
author = "Lev Sychev"
version = "1.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdf66880c1a4081689b6525949451725d49cd4c37d7689baf8c84a66b9a04954"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
